# Book settings
title: Analisis y Diseño II
author: YOUR NAME / YOUR INSTITUTION
logo: content/local/imgs/rlxmooc_logo-black.png

repository:
   url: https://github.com/rramosp/xxx
   branch: main

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

#html:
#  google_analytics_id: "XXXX"

execute:
  execute_notebooks         : off

